### ISSUE TITLE
Players with low FPS can sometimes walk through walls.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#108] opened 2016-01-24 15:41 UTC
Several players are reporting if they have <10 FPS in Ogre they can move on top of buildings and through some walls (e.g. on top of Fams, and through the fence near the Streets of Tos flagpole).

**Comment by cyberjunk** [comment] 2016-01-24 20:19
Interesting. Not sure what's the problem so far exactly.
Movements are calculated on a per-frame-base.
Problem might be related to an error on the move-validation due to rather long vectors on very low FPS. But honestly I would have expected issues more likely with very short vectors (e.g. 1000 FPS).

**Comment by tyras2** [comment] 2017-05-27 07:22
Yes, i can confirm this behavior. Afaik that bug spread around and people trying to drop the fps by launching programms that kills a lot of fps so they can walk through walls and trying to get advantages in PvP.

**Comment by cyberjunk** [comment] 2017-05-27 10:38
I have not been able to reproduce this, so it's hard to fix...

The server already denies movements which go to locations outside of any ROO sector.
This prevents a great part of all wallhacking already, regardless of the client.

What you can still from the server side is illegally step up onto a roof (e.g. fams).

We can't prevent this without either:
(a) removing all jumps from the game (unrealistic)
(b) tracking and incrementing object's heights on the serverside over time rather than assuming everything on ground height in calculations.

I don't really see why lagging your client to low FPS gives any advantage in PvP...
I would rather be afraid of people disabling the collision checks in their client.
Regardless whether it's classic or ogre.

Ideally we should implement (b) on the server-side.

**Comment by cyberjunk** [comment] 2018-09-04 14:48
Closing this, should be fixed in multiple ways by now:
1) New client-side move validation prevents this.
2) For 105/112 the server-side move validation additionally prevents this.

**Closed by cyberjunk** 2018-09-04 14:48 UTC
Labels: bug
