### ISSUE TITLE
No nightvision with shadow amulet

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#38] opened 2015-05-16 00:13 UTC
Is it wanted that wearing a shadow amulet causes kra night vision to be disfunctional ?
I accidently picked one up in the orc caves and everything went dark while having nightvision active.
Recasting night vision or changing the map didn't help at all.

**Comment by cyberjunk** [comment] 2015-05-16 02:44
I DO think that an amulet of shadow is supposed to make everything a BIT darker, but I don't think it's supposed to completely negate night vision :-)

Will have a look at that.

**Comment by AlgorithmsOfMathdestruction** [comment] 2015-05-16 11:22
Well I can't give further detail yet :/ My monitor is a 120hz gaming thing with bad colors/contrast and I can't swap the client window to my other monitor for testing it there.

**Comment by cyberjunk** [comment] 2015-05-16 15:04
>> I can't swap the client window to my other monitor for testing it there.

Moving the game window across monitors in multi-display setups will create an huge freeze, but it should actually work. Just be patient and don't touch the window after you've moved it (may take up to ~30 secs or more to recover). You can also change the monitor the gamewindow comes up in the Options (restart required).

**Comment by cyberjunk** [comment] 2015-07-19 17:20
I was not able to reproduce this with 1.0.3.7 in orc-caves.

I tried looting an amulet of Shadows while night-vision was on: As expected my screen only went slightly darker. Night-vision still worked.

I also tried to cast night-vision after the amulet of Shadows was already equipped and the screen was fully dark. This also made it bright as expected.

Please try to test again with latest 1.0.3.7 and possibly close this ticket, leaving it open for now.

**Comment by cyberjunk** [comment] 2015-07-24 22:33
As mentioned I wasn't able to reproduce this, also not with current 1.0.3.8.
Amulet of Shadows only slightly lowers the effect of night-vision for me.

Closing this ticket, please reopen if you can still reproduce this bug.

**Closed by cyberjunk** 2015-07-24 22:33 UTC
Labels: bug
