### ISSUE TITLE
Bug: Glow doesnt work in 1st person view on map change / first load

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#25] opened 2015-05-10 21:10 UTC
If you play in first person view, your light from glow wont work if you change the map or load the game the first time. you have to re-use your weapon or switch to 3rd-person-view to activate the lighting.

**Comment by cyberjunk** [comment] 2015-05-18 11:55
Confirmed and will be fixed in 1.0.3.6

The light was turned invisible when the parent scenenode (your avatar) was turned invisible due to 1.person mode.

**Comment by cyberjunk** [comment] 2015-07-19 18:10
Closing this. Should be fixed in the current versions.

**Closed by cyberjunk** 2015-07-19 18:10 UTC
Labels: bug
