### ISSUE TITLE
Flagpoles make it hard to select anything near them

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#42] opened 2015-05-16 17:57 UTC
If you try to fight soldiers, it will always target the flagpole first. the only way to select soldiers is to TAB through them. 

![image](https://cloud.githubusercontent.com/assets/12058341/7667396/2d60127c-fc06-11e4-8eda-889b2189a1d4.png)

**Comment by cyberjunk** [comment] 2015-05-16 19:24
This is basically a duplicate of:
https://github.com/cyberjunk/meridian59-dotnet/issues/4

**Comment by skittles1** [comment] 2015-05-17 09:41
Flagpoles specifically have a giant transparent area (192px wide, flagpole itself is like 8px). I'm uploading a 16px wide version for the next update that will help this issue, though the bounding box includes the flag as well so it's more of an improvement than an actual fix.

**Comment by cyberjunk** [comment] 2017-04-11 16:52
Closing this. The original issue (see above) for the big boundingboxes is still open.

**Closed by cyberjunk** 2017-04-11 16:52 UTC
Labels: duplicate
