### ISSUE TITLE
Editboxes in the alias window don't permit pasting content.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#168] opened 2016-08-07 14:22 UTC
Also, in the group tab, only the new group editbox allows pasting of content, the new member editbox doesn't.

It is, however, possible to copy from all editboxes, even the ones that don't allow pasting.

**Comment by cyberjunk** [comment] 2018-09-07 17:29
Fixed in: https://github.com/cyberjunk/meridian59-dotnet/commit/53191d642044524e8821db4997172e415de3fba4

Bug only happened in X64.
Caused by 'MaxTextLength' being MAXINT64 and somehow causing trouble.
Fixed by setting a high, but still valid int32 value as default.

**Closed by cyberjunk** 2018-09-07 17:29 UTC
Labels: enhancement
