### ISSUE TITLE
Separate tabs for chat and combat.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#179] opened 2016-08-30 21:32 UTC
People would like a way to keep combat spam and chat separate. Possibly, a few thousand lines of chat history would help as well.

**Comment by cyberjunk** [comment] 2017-04-11 16:39
I'm closing this, because it's basically a duplicate of:
https://github.com/cyberjunk/meridian59-dotnet/issues/24

**Closed by cyberjunk** 2017-04-11 16:39 UTC
