### ISSUE TITLE
ActionButton assignments lost on 'quit'

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#183] opened 2016-08-31 19:30 UTC
Title says it all. :)

**Comment by cyberjunk** [comment] 2016-09-25 16:10
Is this still relevant?
If yes, can you be a bit more specific 'what' to save?

I think the configuration.xml is indeed only written when the client is actually closed..

However 'quit' should definitely save other things like new Aliases, Groups, Keybindings or modified buttongrid assignments...

**Comment by MorbusM59** [comment] 2016-09-25 19:51
I think that was it really.

If you rearrange actionbuttons, then quit, then log back in, your actionbuttons will revert back to how they were before. Quite annoying if you want to sort out actionbuttons on multiple characters. You have to quit and load up the client every time.

**Comment by cyberjunk** [comment] 2016-09-25 20:30
>> If you rearrange actionbuttons, then quit, then log back in, your actionbuttons will revert back to how they were before

Ok, that's a bug then.

**Comment by cyberjunk** [comment] 2017-04-11 17:03
This bug still exists:
>> If you rearrange actionbuttons, then quit, then log back in, your actionbuttons will revert back to how they were before.

**Comment by cyberjunk** [comment] 2017-06-01 20:20
Closing this because duplicate of https://github.com/cyberjunk/meridian59-dotnet/issues/232
Already fixed.

**Closed by cyberjunk** 2017-06-01 20:20 UTC
Labels: bug
