### ISSUE TITLE
"afxres.h" include problem VisualStudio Desktop/Community (free)

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#41] opened 2015-05-16 11:45 UTC
Trying to build meridian59-dotnet in a freeware VisualStudio like 2013Desktop or CommunityEdition
causes a very few include errors about "afxres.h"

I actually fixed this locally by setting a preprocessor flag "_VSFREE" and doing the following changes to this parts:

Lib: FreeImage
File: FreeImage.rc line 9

//#include "afxres.h"
#ifdef _VSFREE
#include "WinResrc.h"
#define IDC_STATIC  -1
#else
#include "afxres.h"
#endif

Project: Ogre Client
File: app.rc line 11

//#include "afxres.h"
#ifdef _VSFREE
#include "WinResrc.h"
#define IDC_STATIC  -1
#else
#include "afxres.h"
#endif

**Comment by cyberjunk** [comment] 2015-05-16 15:24
Interesting....
I can replace

>> #include "afxres.h"

with

>> #include "WinResrc.h"

and it still compiles just fine in VS 2013 Ultimate.
So I will probably just replace these includes, if it fixes the free edition...

But the problem is these .RC files get overwritten by VS resource designer (double-click the RC in the project solution to open it in the designer, change something and save it). So I have to keep this in mind and reapply the include change whenever I, for example, raise the application version...

**Comment by cyberjunk** [comment] 2015-05-16 15:25
Oh, out of curiosity:
Could you please open the .RC file in the resource designer of the free edition and press save?

How does this change the afxres.h include? Or does it complain when opening the .RC ?

**Comment by cyberjunk** [comment] 2015-05-16 15:35
I also found in the 'OgreWin32Resources.rc' in 'OgreMain' project of the Engine solution the following include:

>> #include "winres.h"

Rather than the afxres.h..
The file also seems to be designer created - does this project compile fine for you?

**Comment by AlgorithmsOfMathdestruction** [comment] 2015-05-16 16:27
On double clicking the .rc it tells me that editing resource files is not possible with Visual C++ Express-SKU.

Chaning the include at FreeImage and Ogre rc-code solved all problems. Everything else compiles without error but some libs throw some warnings. Mostly type conversion loss warnings.
I' able now to compile Debug and Release properly with all resources set up. Playing Meridian launched from VS works flawless.

replacing by "winres.h" should work fine. I also found this file at a later point and ist handles the "Static idc" thing too.

Really impressive that so much connected stuff just works fine after downloading.

**Comment by cyberjunk** [comment] 2015-05-16 16:52
I've commited changes to the engine and main repository which should fix the issues with VS 2013?
Turned the include into:
>> #include "winres.h"

I was also able to fix the issue with the VS designer overwriting this include by also replacing another occurence of 'afxres.h' a bit later in the RC file.

>> 2 TEXTINCLUDE 
BEGIN
    "#include ""winres.h""\r\n"
    "\0"
END

Please let me know if everything compiles fine now with VS2013 express.

**Comment by AlgorithmsOfMathdestruction** [comment] 2015-05-17 01:00
I got update for ogre app and seems to work but freeimage is still my local version with the #ifdef.
Gotta check tomorrow if git failed to sync the subproject for engine.

**Comment by AlgorithmsOfMathdestruction** [comment] 2015-05-17 12:05
After having problems with getting the subpackage engine updated it's now working again.
Getting the whole dotnet repos from scratch works without any errors.
Only thing I did was changing the debug workpath and getting the meridian objects and grapfics from installed 103 client.

**Comment by cyberjunk** [comment] 2015-05-17 14:33
Great!

>> Only thing I did was changing the debug workpath and getting the meridian objects and grapfics from installed 103 client.

Yes, since the official repo and the 103 repo both do not include the BGF files, I thought it would better do the same and exclude them. Unfortunately the debug-path is part of the "xxxxx.vcxproj.user" file, which to my knowledge should not be added to repositories. I might still do it, because the content of my current .user file does not look like it would cause issues for anyone.

**Comment by cyberjunk** [comment] 2015-05-18 10:56
Seems this is fixed, closing it, unless you have something else to add.

**Closed by cyberjunk** 2015-05-18 10:56 UTC
Labels: bug
