### ISSUE TITLE
Bug: Attacking Animation doesnt work while moving (3rd Person View)

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#32] opened 2015-05-10 22:35 UTC

**Comment by cyberjunk** [comment] 2015-05-16 03:26
Confirmed...
Have to have a look at it in detail, however I think this may be could be solved better on the server-side.

It seems to me the BP_CHANGE, sent from the server when attacking something, only contains the 'attack once' animation in the default suboverlays, not in the movement overlays.

**Comment by cyberjunk** [comment] 2018-09-05 13:10
This was fixed in:
https://github.com/cyberjunk/meridian59-dotnet/commit/1bb9992132d115e83fe5eb6a7ecb78869e7dc966

For now it looks like in classic:
Attacks during moves will show the attack animation, instead of the move animation.
Ideally would need to show both combined (e.g. moving legs + attacking arms).

**Closed by cyberjunk** 2018-09-05 13:10 UTC
Labels: bug
