### ISSUE TITLE
System-Safe and Globe Posting

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#233] opened 2017-05-27 07:09 UTC
When you're writing a longer globe posting, and theres a system-safe coming the window get closed and you can start again to write your post. Maybe there is an option to fix this issue (Guess it's also an problem in classic)

**Comment by cyberjunk** [comment] 2017-05-27 10:30
Closing this because duplicate of https://github.com/cyberjunk/meridian59-dotnet/issues/164

**Closed by cyberjunk** 2017-05-27 10:30 UTC
