### ISSUE TITLE
Size and pos of chat and invent window gets always reseted

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#40] opened 2015-05-16 00:28 UTC
It would be nice when chat and inventory window keep their last used position and size on client restart.

**Comment by cyberjunk** [comment] 2015-05-16 02:12
Duplicate of https://github.com/cyberjunk/meridian59-dotnet/issues/2

Thanks anyways :)

**Closed** 2015-05-16 02:12 UTC
