### ISSUE TITLE
Quit won't return to login when quitting in safe places.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#88] opened 2015-12-29 12:25 UTC
Not 100% sure if the safe place is the issue but it will take me to login when logging out in Tos streets, but not in Familiars.

**Comment by m59solo** [comment] 2015-12-29 12:48
maybe connected to #55

**Comment by cyberjunk** [comment] 2016-01-24 20:40
I wasn't able to reproduce this, may be I misunderstand it.
First let me point out that the client does not directly know what's a safe place and what's not. So I think it's very unlikely this is related to the location you are testing...

The chatcommand "quit" is supposed to always kick you back to your avatar selection screen.
This seems to work fine for me no matter what location I was...

**Comment by Rayz0r** [comment] 2016-02-07 09:00
I am also having this issue, it seems to be Windows 10 specific. There is a bad command issued when you type quite (Can't use the X as window mode does not work on Windows 10). This crashes the client and you must restart it to log back in. Makes character swapping painful.

**Comment by skittles1** [comment] 2016-09-22 09:18
Think some of these issues were related to #201?

**Comment by cyberjunk** [comment] 2016-09-22 09:30
Yes, very likely the cause for this one is described in https://github.com/cyberjunk/meridian59-dotnet/issues/201

Closing this.

**Closed by cyberjunk** 2016-09-22 09:30 UTC
Labels: question
