### ISSUE TITLE
Right click resets to hotkey 25 after restart.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#87] opened 2015-12-29 12:24 UTC
Nothing to add.

**Comment by m59solo** [comment] 2015-12-29 12:41
i can confirm that behavior

and an option to disable right click-mapping completely would be cool. Because its already used for freelook and walking. I often accidentally execute the mapped hotkey and have to left it unmapped because of this

**Comment by cyberjunk** [comment] 2015-12-30 15:16
Reset after restart will be fixed in next version.

**Comment by cyberjunk** [comment] 2016-01-24 19:46
Closing this, should be fixed in latest version (use OpenMeridian patcher).

**Closed by cyberjunk** 2016-01-24 19:46 UTC
Labels: bug
