### ISSUE TITLE
Sound bug if volume is lower than 100%

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#54] opened 2015-05-28 17:16 UTC
Sound seems cut off when you use the volume slider, check my video for a demonstration. First milisecond is 100% volume, after that it gets faded out to the chosen volume. At 100% its fine though

https://www.youtube.com/watch?v=nzyQqdDZszA

**Comment by cyberjunk** [comment] 2015-07-09 13:56
I think after lot of more testing I am able to reproduce this.
But I need to turn my sound volume at least lower than 50% to make it notable.

As a workaround:
(a) set the sound volume to max in game
(b) use windows sound mixer to get your favorite sound level
(c) use the music slider to make turn music down/off

**Comment by cyberjunk** [comment] 2016-09-04 17:28
This might have been fixed in: https://github.com/cyberjunk/meridian59-dotnet/commit/5aa4d16875948e38030304806a5289d255010017

The sound was actually started and then the volume was set afterwards. Due to the irrklang lib running its own thread, it's possible the playback is at 100% for a very short time. Now playback will start after volume has been set. Hopefully fixing this.

**Comment by cyberjunk** [comment] 2017-04-11 16:41
Closing this. Should be fixed in mentioned commit.

**Closed by cyberjunk** 2017-04-11 16:41 UTC
Labels: bug
